//! `dent8 export --target <FILE>` and `dent8 import <FILE>`: the native-memory **write path**
//! between the dent8 fact store and provider-native memory files (`CLAUDE.md`, `AGENTS.md`,
//! `GEMINI.md`, `.cursor/rules`, …).
//!
//! Both halves go *through* the existing firewall, never around it:
//!
//! - **Export** renders the currently-believed facts (the same belief/freshness/contested
//!   selection `dent8 context` uses) into a delimited **managed block** and splices it
//!   idempotently into the target file. It writes the file from the CLI process itself — the
//!   sanctioned channel the `Write`/`Edit`-scoped `PreToolUse` guard does not intercept — and
//!   every rendered line carries a `dent8://<kind>/<key>/<predicate>` receipt marker plus the
//!   believed event's id and hash, so `native scan`/`reconcile` (and the guard's
//!   `post-write-audit` mode) recognize the block as dent8-managed rather than unmanaged drift.
//! - **Import** parses durable facts out of a memory file with deterministic, documented rules
//!   (no LLM, no fabrication) and routes **every** recovered proposal through the exact same
//!   `capture::apply_proposal` funnel the `capture` command uses — so an imported fact cannot
//!   smuggle itself past authority, policy, or the content check.
//!
//! ## Managed-block format
//!
//! ```text
//! <!-- BEGIN dent8 managed block (generated by `dent8 export`; edits inside are overwritten) -->
//! <!-- dent8 export: 2 believed fact(s); do not edit inside this block — run `dent8 export --target <file>` to refresh -->
//!
//! ### repo:dent8
//! - `dent8://repo/dent8/test_command` = "cargo test"  <!-- dent8 receipt fact=fact:repo:dent8:test_command:1 event_hash=abcd… authority=medium source=source:human -->
//! <!-- END dent8 managed block -->
//! ```
//!
//! Each fact line puts the authoritative data in the `dent8://kind/key/predicate` marker plus
//! the rendered value; import recovers subject/predicate/value from exactly those, which is what
//! makes the round-trip stable.
//!
//! ## Import rules
//!
//! 1. **Managed block** (inverse of export): each fact line inside a `dent8` managed block →
//!    an `assert` proposal recovered from the marker + rendered value.
//! 2. **Inline receipt markers in prose**: a line anywhere carrying a `dent8://kind/key/predicate`
//!    marker followed by `= <value>` → an `assert` proposal (lets a human hand-annotate facts).
//! 3. **Fenced `dent8` code block**: a fenced block tagged ```` ```dent8 ```` whose lines are JSON
//!    `Proposal`s (the same format `capture` reads) → proposals, applied verbatim.
//!
//! Everything else (free prose, headings, arbitrary bullets, other code fences) is **skipped**
//! and reported — import never invents a fact.

use std::fmt::Write as _;
use std::path::Path;

use dent8_core::FactValue;

use crate::{
    CliAuthority, CliOutput, CliStream, ContextArgs, ImportArgs,
    context::{ContextFact, ContextOutcome, context_outcome},
    log_path,
    ops::{FactFreshness, OpError, op_error_exit_code, op_error_json},
    paint_status, print_json_stdout, print_json_stdout_with_code,
    status::Status,
};

/// Opening delimiter of the dent8-managed block. Recognized by
/// [`crate::native`]'s receipt-marker audit so a generated block reads as sanctioned.
pub(crate) const BEGIN_SENTINEL: &str = "<!-- BEGIN dent8 managed block (generated by `dent8 export`; edits inside are overwritten) -->";
/// Closing delimiter of the dent8-managed block.
pub(crate) const END_SENTINEL: &str = "<!-- END dent8 managed block -->";

/// The metadata comment that trails each managed-block fact line; import splits the rendered
/// value from the receipt on this token so a value can safely contain `<!--`.
const RECEIPT_COMMENT_PREFIX: &str = "  <!-- dent8 receipt";

// =====================================================================================
// Export: render believed facts into an idempotently-spliced managed block.
// =====================================================================================

/// Encode a believed value for a managed-block line so that [`decode_block_value`] recovers it
/// exactly. `Text` becomes a JSON string (escaped, self-delimiting); `Json` is rendered with a
/// `json:` prefix; a `Redacted` value is never written to a plaintext memory file (returns
/// `None`, and export counts it as skipped).
fn encode_block_value(value: &FactValue) -> Option<String> {
    match value {
        FactValue::Text(text) => serde_json::to_string(text).ok(),
        FactValue::Json(json) => Some(format!("json:{}", json.as_str())),
        FactValue::Redacted => None,
    }
}

/// How the target file changed.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
enum BlockOutcome {
    /// The file did not exist; it now contains just the block.
    Created,
    /// The file existed with no sentinels; the block was appended after the existing content.
    Appended,
    /// The file already had a managed block; only its content was replaced.
    Refreshed,
}

impl BlockOutcome {
    fn as_str(self) -> &'static str {
        match self {
            Self::Created => "created",
            Self::Appended => "appended",
            Self::Refreshed => "refreshed",
        }
    }
}

/// Render the currently-believed facts into a managed block (delimited by the sentinels, no
/// trailing newline). Returns the block text and the count of believed facts skipped because
/// their value is redacted.
fn render_managed_block(outcome: &ContextOutcome) -> (String, usize) {
    let mut body = String::new();
    let mut redacted = 0usize;
    let mut emitted = 0usize;
    let mut current_subject: Option<String> = None;
    for fact in outcome.facts() {
        let Some(encoded) = encode_block_value(fact.value()) else {
            redacted += 1;
            continue;
        };
        let subject = format!("{}:{}", fact.subject_kind(), fact.subject_key());
        if current_subject.as_deref() != Some(subject.as_str()) {
            let _ = write!(body, "\n### {subject}\n\n");
            current_subject = Some(subject);
        }
        let _ = writeln!(
            body,
            "- `{}` = {}{} authority={} source={} -->{}",
            fact.uri(),
            encoded,
            format_args!(
                "  <!-- dent8 receipt fact={} event_hash={}",
                fact.fact_id(),
                crate::short(fact.event_hash())
            ),
            fact.authority().name(),
            fact.source().unwrap_or("-"),
            fact_markers(fact),
        );
        emitted += 1;
    }

    let mut out = String::new();
    out.push_str(BEGIN_SENTINEL);
    out.push('\n');
    let _ = writeln!(
        out,
        "<!-- dent8 export: {emitted} believed fact(s); do not edit inside this block — run \
         `dent8 export --target <file>` to refresh -->"
    );
    if emitted == 0 {
        out.push_str(
            "\n_No believed facts to export yet — seed them with `dent8 assert` or \
             `dent8 import`._\n",
        );
    } else {
        out.push_str(&body);
    }
    out.push('\n');
    out.push_str(END_SENTINEL);
    (out, redacted)
}

/// Cosmetic flags appended after a fact line (import ignores them). Export only ever emits fresh,
/// non-terminal facts, so `contested` is the only flag that can appear.
fn fact_markers(fact: &ContextFact) -> String {
    let mut markers = String::new();
    if fact.contested_by() > 0 {
        let _ = write!(
            markers,
            "  **[contested — {} rival value(s); run `dent8 conflicts` before relying on this]**",
            fact.contested_by()
        );
    }
    if fact.freshness() == FactFreshness::Stale {
        markers.push_str("  **[stale — past its validity window]**");
    }
    markers
}

/// The target file's dominant line ending: `\r\n` when CRLF strictly outnumbers lone `\n`,
/// otherwise `\n`. A new/empty file, or one with no newlines, defaults to LF so fresh files keep
/// the historical behavior and tests stay deterministic.
fn dominant_line_ending(existing: &str) -> &'static str {
    let crlf = existing.matches("\r\n").count();
    let lf = existing.matches('\n').count().saturating_sub(crlf);
    if crlf > lf { "\r\n" } else { "\n" }
}

/// If `trimmed` (already left-trimmed) opens or closes a Markdown code fence, return its fence
/// char (`` ` `` or `~`) and run length. A line whose trimmed content starts with 3+ backticks or
/// 3+ tildes is a fence line; `` ` `` and `~` are ASCII so `run` is also a valid byte offset.
fn code_fence(trimmed: &str) -> Option<(char, usize)> {
    let ch = trimmed.chars().next()?;
    if ch != '`' && ch != '~' {
        return None;
    }
    let run = trimmed.chars().take_while(|&c| c == ch).count();
    (run >= 3).then_some((ch, run))
}

/// Byte offsets of the BEGIN and END sentinels that sit **outside** any fenced code block, plus
/// whether the file ends **inside an unclosed fence**. Sentinels inside a ```` ``` ````/`~~~`
/// fenced code block — e.g. the documented example block in `docs/native-memory.md` — are ignored
/// so they are never mistaken for the live managed block and overwritten. Fence state toggles on
/// an opening fence and clears on a bare closing fence of the same char that is at least as long
/// (a robust subset of `CommonMark` that handles the common cases without panicking). Fence
/// awareness only covers fenced code blocks, not 4-space-indented code blocks. When the last line
/// leaves a fence open, `unclosed_fence` is true so the caller can refuse to append a managed block
/// that would land inside the never-closed fence.
struct ManagedBlockScan {
    begins: Vec<usize>,
    ends: Vec<usize>,
    unclosed_fence: bool,
}

fn managed_block_sentinels(existing: &str) -> ManagedBlockScan {
    let mut begins = Vec::new();
    let mut ends = Vec::new();
    let mut fence: Option<(char, usize)> = None;
    let mut offset = 0usize;
    for segment in existing.split_inclusive('\n') {
        let line = segment.trim_end_matches('\n').trim_end_matches('\r');
        let trimmed = line.trim_start();
        if let Some((ch, run)) = code_fence(trimmed) {
            match fence {
                // A bare closing fence of the same char, at least as long as the opener.
                Some((open_ch, open_run))
                    if ch == open_ch && run >= open_run && trimmed[run..].trim().is_empty() =>
                {
                    fence = None;
                }
                // A fence-looking line that is not a valid closer stays inside the fence.
                Some(_) => {}
                None => fence = Some((ch, run)),
            }
        } else if fence.is_none() {
            // The scan records the FIRST sentinel of each kind per line. Sentinels are normally
            // their own HTML-comment lines, so this is exact in practice; a pathological single
            // newline-free line carrying two complete BEGIN…END blocks would be seen as one pair
            // and refreshed rather than refused.
            if let Some(pos) = line.find(BEGIN_SENTINEL) {
                begins.push(offset + pos);
            }
            if let Some(pos) = line.find(END_SENTINEL) {
                ends.push(offset + pos);
            }
        }
        offset += segment.len();
    }
    ManagedBlockScan {
        begins,
        ends,
        unclosed_fence: fence.is_some(),
    }
}

/// Splice the block into the existing file content idempotently. Exactly one well-formed
/// `BEGIN … END` pair (counting only sentinels **outside** fenced code blocks) is replaced in
/// place (everything outside preserved byte-for-byte); a file with no such sentinels gets the
/// block appended (or created). Any *malformed* sentinel arrangement — a `BEGIN` with no matching
/// `END`, an orphan `END`, `END` before `BEGIN`, or duplicate sentinels — is refused rather than
/// appended-to, because appending past an unterminated `BEGIN` would let the next export delete
/// the user's content between the stray `BEGIN` and the new `END`. A file that ends inside an
/// unclosed fenced code block is likewise refused on the append path, because appending would drop
/// the managed block inside that never-closed fence (and each export would then re-append, growing
/// the file). The caller surfaces the error as a nonzero exit and leaves the file untouched. The
/// emitted block (and the newlines joining it to the surrounding text) use the file's dominant line
/// ending so the result stays consistent.
fn splice_managed_block(
    existing: Option<&str>,
    block: &str,
) -> Result<(String, BlockOutcome), String> {
    let Some(existing) = existing else {
        return Ok((format!("{block}\n"), BlockOutcome::Created));
    };
    // Emit the block with the file's dominant ending; the LF-rendered block has no `\r`.
    let ending = dominant_line_ending(existing);
    let owned_block;
    let block: &str = if ending == "\n" {
        block
    } else {
        owned_block = block.replace('\n', ending);
        &owned_block
    };
    let ManagedBlockScan {
        begins,
        ends,
        unclosed_fence,
    } = managed_block_sentinels(existing);
    let stray_sentinel = || {
        Err(
            "found a dent8 BEGIN/END managed-block sentinel that is not exactly one well-formed \
             BEGIN … END pair — refusing to overwrite; fix or remove the stray sentinel"
                .to_string(),
        )
    };
    match (begins.as_slice(), ends.as_slice()) {
        // No managed block yet: append after existing content (or create).
        ([], []) => {
            if existing.is_empty() {
                return Ok((format!("{block}{ending}"), BlockOutcome::Created));
            }
            // Refuse rather than append into a never-closed fence (would nest the block inside it
            // and let each subsequent export re-append, growing the file). Don't mutate the fence.
            if unclosed_fence {
                return Err(
                    "target file ends inside an unclosed code fence — refusing to add a managed \
                     block inside it; close the fence and re-run"
                        .to_string(),
                );
            }
            let separator = if existing.ends_with(&format!("{ending}{ending}")) {
                String::new()
            } else if existing.ends_with('\n') {
                ending.to_string()
            } else {
                format!("{ending}{ending}")
            };
            Ok((
                format!("{existing}{separator}{block}{ending}"),
                BlockOutcome::Appended,
            ))
        }
        // Exactly one well-formed pair (BEGIN before END): replace in place.
        ([begin_start], [end_start]) if begin_start < end_start => {
            let end_after = end_start + END_SENTINEL.len();
            let rest = &existing[end_after..];
            let (replace_end, trailing) = if rest.starts_with("\r\n") {
                (end_after + 2, ending)
            } else if rest.starts_with('\n') {
                (end_after + 1, ending)
            } else {
                (end_after, "")
            };
            let mut result = String::with_capacity(
                existing.len().saturating_sub(end_after) + block.len() + ending.len(),
            );
            result.push_str(&existing[..*begin_start]);
            result.push_str(block);
            result.push_str(trailing);
            result.push_str(&existing[replace_end..]);
            Ok((result, BlockOutcome::Refreshed))
        }
        _ => stray_sentinel(),
    }
}

struct ExportReport {
    target: String,
    facts_written: usize,
    redacted_skipped: usize,
    block: BlockOutcome,
}

fn export_native(target: &Path) -> Result<ExportReport, OpError> {
    let outcome = context_outcome(&log_path(), &ContextArgs::default())?;
    let (block, redacted_skipped) = render_managed_block(&outcome);
    let existing = match std::fs::read_to_string(target) {
        Ok(contents) => Some(contents),
        Err(error) if error.kind() == std::io::ErrorKind::NotFound => None,
        Err(error) => {
            return Err(OpError::rejected(format!(
                "cannot read {}: {error}",
                target.display()
            )));
        }
    };
    let (contents, block_outcome) =
        splice_managed_block(existing.as_deref(), &block).map_err(OpError::rejected)?;
    std::fs::write(target, contents).map_err(|error| {
        OpError::rejected(format!("cannot write {}: {error}", target.display()))
    })?;
    let facts_written = outcome.facts().len().saturating_sub(redacted_skipped);
    Ok(ExportReport {
        target: target.display().to_string(),
        facts_written,
        redacted_skipped,
        block: block_outcome,
    })
}

fn export_text(report: &ExportReport) -> String {
    let mut lines = vec![format!(
        "exported {} believed fact(s) to {}",
        report.facts_written, report.target
    )];
    lines.push(format!(
        "  dent8-managed block {} (dent8:// receipts embedded; the PreToolUse guard blocks \
         hand-edits — re-run `dent8 export --target {}` to refresh)",
        report.block.as_str(),
        report.target
    ));
    if report.redacted_skipped > 0 {
        lines.push(format!(
            "  {} redacted fact(s) skipped (never written to a plaintext memory file)",
            report.redacted_skipped
        ));
    }
    lines.join("\n")
}

fn export_json(report: &ExportReport) -> serde_json::Value {
    serde_json::json!({
        "status": Status::Ok.as_str(),
        "tool": "export",
        "format": "native-memory",
        "target": report.target,
        "facts_written": report.facts_written,
        "redacted_skipped": report.redacted_skipped,
        "block": report.block.as_str(),
    })
}

pub(crate) fn cmd_export_native(target: &Path, output: CliOutput) -> i32 {
    match export_native(target) {
        Ok(report) => match output {
            CliOutput::Text => {
                println!("{}", paint_status(&export_text(&report), CliStream::Stdout));
                0
            }
            CliOutput::Json => print_json_stdout(&export_json(&report)),
        },
        Err(error) => match output {
            CliOutput::Text => crate::ops::present(Err(error)),
            CliOutput::Json => {
                print_json_stdout_with_code(&op_error_json(&error), op_error_exit_code(&error))
            }
        },
    }
}

// =====================================================================================
// Import: parse durable facts from a memory file, route each through the firewall.
// =====================================================================================

/// A durable fact recovered from a receipt marker line (Rule 1 or Rule 2).
struct ParsedReceipt {
    kind: String,
    key: String,
    predicate: String,
    value: String,
    /// Authority/source hints recovered from the receipt metadata comment (used as the
    /// proposal's declared authority/source, still subject to the firewall's final call).
    authority: Option<String>,
    source: Option<String>,
}

/// Does this char end a `dent8://…` URI token? Mirrors `native`'s terminator set so a marker
/// inside backticks, quotes, or brackets is bounded correctly.
fn uri_terminator(ch: char) -> bool {
    ch.is_whitespace()
        || matches!(
            ch,
            '"' | '\'' | '`' | '<' | '>' | '(' | ')' | '[' | ']' | '{' | '}' | ',' | ';'
        )
}

/// Parse hints (`authority=…`, `source=…`) out of a receipt metadata comment region.
fn parse_meta_hints(region: &str) -> (Option<String>, Option<String>) {
    let mut authority = None;
    let mut source = None;
    for token in region.split_whitespace() {
        let token = token.trim_end_matches("-->");
        if let Some(value) = token.strip_prefix("authority=")
            && !value.is_empty()
        {
            authority = Some(value.to_string());
        } else if let Some(value) = token.strip_prefix("source=")
            && !value.is_empty()
        {
            source = Some(value.to_string());
        }
    }
    (authority, source)
}

/// Recover the durable string value from a rendered token. Inverse of [`encode_block_value`];
/// lenient for hand-authored (Rule 2) markers that write a bare value.
fn decode_block_value(token: &str) -> Result<String, String> {
    let token = token.trim();
    if token.is_empty() {
        return Err("receipt marker has no value".to_string());
    }
    if token.starts_with('"') {
        serde_json::from_str::<String>(token)
            .map_err(|error| format!("malformed quoted value: {error}"))
    } else if let Some(rest) = token.strip_prefix("json:") {
        Ok(rest.to_string())
    } else {
        Ok(token.to_string())
    }
}

/// Try to read a fact from a single line carrying a `dent8://` marker.
///
/// - `None`  — no marker, or a marker with no `= <value>` (a bare reference/mention): not a fact.
/// - `Some(Err)` — a marker that looks like a fact but is malformed (reported as skipped/invalid).
/// - `Some(Ok)` — a recovered fact.
fn parse_receipt_line(line: &str) -> Option<Result<ParsedReceipt, String>> {
    let marker_pos = line.find("dent8://")?;
    let tail = &line[marker_pos..];
    let uri_end = tail
        .char_indices()
        .find_map(|(index, ch)| uri_terminator(ch).then_some(index))
        .unwrap_or(tail.len());
    let uri = &tail[..uri_end];
    let Some((kind, key, predicate)) = crate::mcp::parse_resource_uri(uri) else {
        return Some(Err(format!("malformed receipt marker `{uri}`")));
    };
    // The value separator is the first `=` after the URI token.
    let after_uri = marker_pos + uri_end;
    let equals = line[after_uri..].find('=')?;
    let region = line[after_uri + equals + 1..].trim_start();
    // Split the rendered value from the trailing receipt metadata comment. The receipt comment is
    // always the trailing element of a managed-block line, so split on its LAST occurrence — a
    // Text value that itself contains the literal `<!-- dent8 receipt` token then survives intact
    // instead of being truncated (and silently dropped as "skipped").
    let (value_token, meta_region) = match region.rsplit_once(RECEIPT_COMMENT_PREFIX) {
        Some((value, meta)) => (value, meta),
        None => (region, ""),
    };
    let value = match decode_block_value(value_token) {
        Ok(value) => value,
        Err(error) => return Some(Err(error)),
    };
    let (authority, source) = parse_meta_hints(meta_region);
    Some(Ok(ParsedReceipt {
        kind,
        key,
        predicate,
        value,
        authority,
        source,
    }))
}

/// Serialize a recovered receipt as a `capture` proposal JSON line, so it flows through the exact
/// same firewall funnel as `dent8 capture`. Authority/source hints from the marker ride along as
/// declared proposal fields (line-level values, which `resolve_proposal_meta` ranks above flags).
fn receipt_to_proposal_json(receipt: &ParsedReceipt) -> String {
    let mut object = serde_json::Map::new();
    object.insert(
        "subject".to_string(),
        serde_json::Value::String(format!("{}:{}", receipt.kind, receipt.key)),
    );
    object.insert(
        "predicate".to_string(),
        serde_json::Value::String(receipt.predicate.clone()),
    );
    object.insert(
        "value".to_string(),
        serde_json::Value::String(receipt.value.clone()),
    );
    if let Some(authority) = &receipt.authority {
        object.insert(
            "authority".to_string(),
            serde_json::Value::String(authority.clone()),
        );
    }
    if let Some(source) = &receipt.source {
        object.insert(
            "source".to_string(),
            serde_json::Value::String(source.clone()),
        );
    }
    serde_json::Value::Object(object).to_string()
}

/// A single proposal recovered from the file, tagged with the rule that produced it.
struct ImportProposal {
    line: usize,
    rule: &'static str,
    /// The `capture` proposal JSON to route through the firewall.
    json: String,
}

/// A line/section the parser deliberately did not import.
struct SkippedLine {
    line: usize,
    reason: String,
}

struct ParsedFile {
    proposals: Vec<ImportProposal>,
    skipped: Vec<SkippedLine>,
}

/// Deterministically extract proposals (Rules 1–3) from a memory file, recording everything else
/// as skipped. No LLM, no fabrication — a line only becomes a proposal if it matches a rule.
fn parse_import_file(contents: &str) -> ParsedFile {
    let mut proposals = Vec::new();
    let mut skipped = Vec::new();
    let mut in_managed_block = false;
    let mut in_dent8_fence = false;
    let mut in_other_fence = false;

    for (index, line) in contents.lines().enumerate() {
        let line_no = index + 1;
        let trimmed = line.trim();

        if line.contains(BEGIN_SENTINEL) {
            in_managed_block = true;
            continue;
        }
        if line.contains(END_SENTINEL) {
            in_managed_block = false;
            continue;
        }

        // Code-fence tracking: only a ```dent8 fence yields proposals (Rule 3); other fences are
        // opaque so a shell snippet mentioning a path is never misread as a fact.
        if trimmed.starts_with("```") {
            if in_dent8_fence {
                in_dent8_fence = false;
            } else if in_other_fence {
                in_other_fence = false;
            } else if trimmed.trim_start_matches('`').trim() == "dent8" {
                in_dent8_fence = true;
            } else {
                in_other_fence = true;
            }
            continue;
        }

        if in_dent8_fence {
            if trimmed.is_empty() {
                continue;
            }
            // Rule 3: the fenced line is a JSON proposal, applied verbatim through the firewall.
            proposals.push(ImportProposal {
                line: line_no,
                rule: "dent8-block",
                json: trimmed.to_string(),
            });
            continue;
        }

        if in_other_fence || trimmed.is_empty() {
            continue;
        }

        if in_managed_block {
            // Rule 1: managed-block fact lines. Non-fact chrome (headings, the export comment) is
            // block-internal and skipped silently.
            match parse_receipt_line(line) {
                Some(Ok(receipt)) => proposals.push(ImportProposal {
                    line: line_no,
                    rule: "managed-block",
                    json: receipt_to_proposal_json(&receipt),
                }),
                Some(Err(reason)) => skipped.push(SkippedLine {
                    line: line_no,
                    reason,
                }),
                None => {}
            }
            continue;
        }

        // Rule 2: an inline receipt marker in free prose.
        match parse_receipt_line(line) {
            Some(Ok(receipt)) => proposals.push(ImportProposal {
                line: line_no,
                rule: "inline-marker",
                json: receipt_to_proposal_json(&receipt),
            }),
            Some(Err(reason)) => skipped.push(SkippedLine {
                line: line_no,
                reason,
            }),
            None if line.contains("dent8://") => skipped.push(SkippedLine {
                line: line_no,
                reason: "dent8:// reference without a `= <value>` — not a fact".to_string(),
            }),
            None => skipped.push(SkippedLine {
                line: line_no,
                reason: "free prose (no dent8 receipt marker or proposal block)".to_string(),
            }),
        }
    }

    ParsedFile { proposals, skipped }
}

struct ImportLineResult {
    line: usize,
    rule: &'static str,
    status: Status,
    message: String,
}

pub(crate) struct ImportOutcome {
    target: String,
    dry_run: bool,
    results: Vec<ImportLineResult>,
    accepted: usize,
    contested: usize,
    rejected: usize,
    invalid: usize,
    skipped: Vec<SkippedLine>,
}

impl ImportOutcome {
    fn imported(&self) -> usize {
        self.accepted + self.contested
    }

    /// Exit-code contract mirrors `capture`: malformed input dominates (exit 2), then a firewall
    /// rejection (exit 1), then success. Skipped prose never changes the exit code.
    fn overall(&self) -> (Status, i32) {
        if self.invalid > 0 {
            (Status::Invalid, 2)
        } else if self.rejected > 0 {
            (Status::Rejected, 1)
        } else {
            (Status::Ok, 0)
        }
    }
}

/// A short human description of a proposal for `--dry-run` (nothing is applied).
fn describe_proposal(json: &str) -> Result<String, String> {
    let value: serde_json::Value =
        serde_json::from_str(json).map_err(|error| format!("malformed proposal: {error}"))?;
    let op = value
        .get("op")
        .and_then(serde_json::Value::as_str)
        .unwrap_or("assert");
    let subject = value
        .get("subject")
        .and_then(serde_json::Value::as_str)
        .ok_or("proposal is missing a subject")?;
    let predicate = value
        .get("predicate")
        .and_then(serde_json::Value::as_str)
        .ok_or("proposal is missing a predicate")?;
    let rendered = value
        .get("value")
        .and_then(serde_json::Value::as_str)
        .map_or_else(String::new, |value| format!(" = {value:?}"));
    Ok(format!("would {op} {subject} {predicate}{rendered}"))
}

pub(crate) fn import_outcome(
    path: &str,
    target: &Path,
    contents: &str,
    dry_run: bool,
    flag_authority: Option<CliAuthority>,
    flag_source: Option<&str>,
) -> ImportOutcome {
    let parsed = parse_import_file(contents);
    let mut outcome = ImportOutcome {
        target: target.display().to_string(),
        dry_run,
        results: Vec::new(),
        accepted: 0,
        contested: 0,
        rejected: 0,
        invalid: 0,
        skipped: parsed.skipped,
    };
    for proposal in &parsed.proposals {
        if dry_run {
            let (status, message) = match describe_proposal(&proposal.json) {
                Ok(message) => (Status::Ok, message),
                Err(message) => {
                    outcome.invalid += 1;
                    (Status::Invalid, message)
                }
            };
            outcome.results.push(ImportLineResult {
                line: proposal.line,
                rule: proposal.rule,
                status,
                message,
            });
            continue;
        }
        let (status, message) = match crate::capture::apply_proposal(
            path,
            &proposal.json,
            flag_authority,
            flag_source,
            &crate::WriteIdentity::Env,
        ) {
            Ok(message) if message.starts_with("CONTESTED") => {
                outcome.contested += 1;
                (Status::Contested, message)
            }
            Ok(message) => {
                outcome.accepted += 1;
                (Status::Accepted, message)
            }
            Err(OpError::Invalid { message, .. }) => {
                outcome.invalid += 1;
                (Status::Invalid, message)
            }
            Err(OpError::Rejected { message, .. } | OpError::Conflict(message)) => {
                outcome.rejected += 1;
                (Status::Rejected, message)
            }
        };
        outcome.results.push(ImportLineResult {
            line: proposal.line,
            rule: proposal.rule,
            status,
            message,
        });
    }
    outcome
}

fn format_import(outcome: &ImportOutcome) -> String {
    let mut lines = Vec::new();
    for result in &outcome.results {
        lines.push(format!(
            "line {} [{}]: {}",
            result.line,
            result.rule,
            crate::first_line(&result.message)
        ));
    }
    if outcome.dry_run {
        lines.push(format!(
            "dry run over {}: {} proposal(s) would be imported, {} malformed, {} line(s) skipped \
             (nothing written)",
            outcome.target,
            outcome.results.len().saturating_sub(outcome.invalid),
            outcome.invalid,
            outcome.skipped.len()
        ));
    } else {
        lines.push(format!(
            "imported {} from {}: {} accepted, {} contested, {} rejected, {} invalid, {} skipped",
            outcome.imported(),
            outcome.target,
            outcome.accepted,
            outcome.contested,
            outcome.rejected,
            outcome.invalid,
            outcome.skipped.len()
        ));
    }
    // A capped sample of skip reasons so a mostly-prose file does not flood the report.
    for skip in outcome.skipped.iter().take(5) {
        lines.push(format!("  skipped line {}: {}", skip.line, skip.reason));
    }
    if outcome.skipped.len() > 5 {
        lines.push(format!(
            "  … and {} more skipped",
            outcome.skipped.len() - 5
        ));
    }
    lines.join("\n")
}

fn import_json(outcome: &ImportOutcome) -> serde_json::Value {
    let (status, _) = outcome.overall();
    serde_json::json!({
        "status": status.as_str(),
        "tool": "import",
        "target": outcome.target,
        "dry_run": outcome.dry_run,
        "imported": outcome.imported(),
        "accepted": outcome.accepted,
        "contested": outcome.contested,
        "rejected": outcome.rejected,
        "invalid": outcome.invalid,
        "skipped": outcome.skipped.len(),
        "results": outcome
            .results
            .iter()
            .map(|result| {
                serde_json::json!({
                    "line": result.line,
                    "rule": result.rule,
                    "status": result.status.as_str(),
                    "message": result.message,
                })
            })
            .collect::<Vec<_>>(),
        "skipped_lines": outcome
            .skipped
            .iter()
            .map(|skip| {
                serde_json::json!({
                    "line": skip.line,
                    "reason": skip.reason,
                })
            })
            .collect::<Vec<_>>(),
    })
}

pub(crate) fn cmd_import(args: &ImportArgs, output: CliOutput) -> i32 {
    let contents = match std::fs::read_to_string(&args.file) {
        Ok(contents) => contents,
        Err(error) => {
            let message = format!("cannot read {}: {error}", args.file.display());
            return match output {
                CliOutput::Text => {
                    eprintln!("{message}");
                    2
                }
                CliOutput::Json => print_json_stdout_with_code(
                    &serde_json::json!({
                        "status": Status::Invalid.as_str(),
                        "tool": "import",
                        "message": message,
                    }),
                    2,
                ),
            };
        }
    };
    let outcome = import_outcome(
        &log_path(),
        &args.file,
        &contents,
        args.dry_run,
        args.authority,
        args.source.as_deref(),
    );
    let (_, code) = if outcome.dry_run {
        // A dry run reports what would happen; only malformed input is a hard error.
        if outcome.invalid > 0 {
            (Status::Invalid, 2)
        } else {
            (Status::Ok, 0)
        }
    } else {
        outcome.overall()
    };
    match output {
        CliOutput::Text => {
            let text = format_import(&outcome);
            if code == 0 {
                println!("{}", paint_status(&text, CliStream::Stdout));
            } else {
                eprintln!("{}", paint_status(&text, CliStream::Stderr));
            }
            code
        }
        CliOutput::Json => {
            if code == 0 {
                print_json_stdout(&import_json(&outcome))
            } else {
                print_json_stdout_with_code(&import_json(&outcome), code)
            }
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use dent8_core::CanonicalJson;

    fn temp_log(name: &str) -> String {
        let dir =
            std::env::temp_dir().join(format!("dent8-memory-unit-{}-{name}", std::process::id()));
        std::fs::create_dir_all(&dir).expect("create temp dir");
        dir.join("log.jsonl").to_string_lossy().into_owned()
    }

    #[test]
    fn encode_decode_round_trips_text_values() {
        for raw in [
            "postgres",
            "cargo test --workspace",
            "has \"quotes\" and <!-- markup",
        ] {
            let encoded =
                encode_block_value(&FactValue::Text(raw.to_string())).expect("text value encodes");
            let decoded = decode_block_value(&encoded).expect("encoded text decodes");
            assert_eq!(decoded, raw, "round-trip through `{encoded}`");
        }
    }

    #[test]
    fn json_values_encode_and_redacted_is_skipped() {
        let json = FactValue::Json(CanonicalJson::new("{\"b\":2,\"a\":1}").expect("canonical"));
        let encoded = encode_block_value(&json).expect("json value encodes");
        assert!(encoded.starts_with("json:"), "{encoded}");
        // Canonicalization sorts keys, so decode yields the compact canonical form.
        let decoded = decode_block_value(&encoded).expect("json decodes");
        assert_eq!(decoded, "{\"a\":1,\"b\":2}");
        assert!(encode_block_value(&FactValue::Redacted).is_none());
    }

    #[test]
    fn parse_receipt_line_recovers_subject_predicate_and_value() {
        let line = "- `dent8://repo/dent8/test_command` = \"cargo test\"  \
                    <!-- dent8 receipt fact=fact:repo:dent8:test_command:1 event_hash=abc… \
                    authority=medium source=source:human -->";
        let parsed = parse_receipt_line(line)
            .expect("line has a marker")
            .expect("marker is well-formed");
        assert_eq!(parsed.kind, "repo");
        assert_eq!(parsed.key, "dent8");
        assert_eq!(parsed.predicate, "test_command");
        assert_eq!(parsed.value, "cargo test");
        assert_eq!(parsed.authority.as_deref(), Some("medium"));
        assert_eq!(parsed.source.as_deref(), Some("source:human"));
    }

    #[test]
    fn parse_receipt_line_handles_bare_and_malformed_markers() {
        // A bare reference (no `= value`) is not a fact.
        assert!(parse_receipt_line("see dent8://repo/dent8/test_command for details").is_none());
        // A prose line with no marker at all.
        assert!(parse_receipt_line("just some prose").is_none());
        // A malformed marker that still looks like a fact is a reported error, not a panic.
        let malformed =
            parse_receipt_line("- `dent8://only-two/segments` = \"x\"").expect("has a marker");
        assert!(malformed.is_err(), "two-segment URI must be rejected");
    }

    #[test]
    fn parse_import_file_applies_each_rule_and_skips_prose() {
        let contents = format!(
            "# My project notes\n\
             Some free prose that must be skipped.\n\
             \n\
             Inline: dent8://repo/demo/build_tool = \"cargo\"\n\
             \n\
             ```dent8\n\
             {{\"subject\":\"repo:demo\",\"predicate\":\"uses_database\",\"value\":\"postgres\"}}\n\
             ```\n\
             \n\
             {BEGIN_SENTINEL}\n\
             <!-- dent8 export: 1 believed fact(s) -->\n\
             ### repo:demo\n\
             - `dent8://repo/demo/test_command` = \"cargo test\"  <!-- dent8 receipt \
             fact=fact:repo:demo:test_command:1 event_hash=abc authority=medium \
             source=source:human -->\n\
             {END_SENTINEL}\n"
        );
        let parsed = parse_import_file(&contents);
        let rules: Vec<&str> = parsed.proposals.iter().map(|p| p.rule).collect();
        assert_eq!(rules, ["inline-marker", "dent8-block", "managed-block"]);
        assert!(
            parsed
                .skipped
                .iter()
                .any(|s| s.reason.contains("free prose")),
            "prose must be reported skipped: {:?}",
            parsed.skipped.iter().map(|s| &s.reason).collect::<Vec<_>>()
        );
    }

    #[test]
    fn import_routes_every_rule_through_the_firewall() {
        let log = temp_log("import-rules");
        let contents = concat!(
            "Inline: dent8://repo/demo/build_tool = \"cargo\"\n",
            "```dent8\n",
            "{\"subject\":\"repo:demo\",\"predicate\":\"uses_database\",\"value\":\"postgres\"}\n",
            "```\n",
        );
        let outcome = import_outcome(&log, Path::new("CLAUDE.md"), contents, false, None, None);
        assert_eq!(outcome.accepted, 2, "{}", format_import(&outcome));
        let persisted = std::fs::read_to_string(&log).expect("read log");
        assert!(persisted.contains("build_tool"), "{persisted}");
        assert!(persisted.contains("uses_database"), "{persisted}");
    }

    #[test]
    fn dry_run_reports_without_writing() {
        let log = temp_log("import-dry-run");
        let contents = "Inline: dent8://repo/demo/build_tool = \"cargo\"\n";
        let outcome = import_outcome(&log, Path::new("CLAUDE.md"), contents, true, None, None);
        assert_eq!(outcome.results.len(), 1);
        assert_eq!(outcome.results[0].status, Status::Ok);
        assert!(outcome.results[0].message.contains("would assert"));
        assert!(
            !std::path::Path::new(&log).exists(),
            "dry run must not create the store"
        );
    }

    #[test]
    fn splice_creates_appends_and_refreshes_preserving_human_text() {
        let block = "<!-- BEGIN dent8 managed block (generated by `dent8 export`; edits inside are overwritten) -->\nX\n<!-- END dent8 managed block -->";
        assert_eq!(
            BEGIN_SENTINEL,
            "<!-- BEGIN dent8 managed block (generated by `dent8 export`; edits inside are overwritten) -->"
        );

        // Created.
        let (created, kind) = splice_managed_block(None, block).expect("create");
        assert_eq!(kind, BlockOutcome::Created);
        assert_eq!(created, format!("{block}\n"));

        // Appended after existing prose (existing bytes preserved).
        let existing = "# Title\n\nHuman prose.\n";
        let (appended, kind) = splice_managed_block(Some(existing), block).expect("append");
        assert_eq!(kind, BlockOutcome::Appended);
        assert!(appended.starts_with(existing), "{appended}");
        assert!(appended.contains(block), "{appended}");

        // Refreshed: replace only the block, preserve prose before AND after byte-for-byte.
        let before = "# Title\n\nBefore prose.\n\n";
        let after = "\nAfter prose that must survive.\n";
        let old_block = "<!-- BEGIN dent8 managed block (generated by `dent8 export`; edits inside are overwritten) -->\nOLD\n<!-- END dent8 managed block -->";
        let file = format!("{before}{old_block}{after}");
        let (refreshed, kind) = splice_managed_block(Some(&file), block).expect("refresh");
        assert_eq!(kind, BlockOutcome::Refreshed);
        assert!(
            refreshed.starts_with(before),
            "before not preserved:\n{refreshed}"
        );
        assert!(
            refreshed.ends_with(after),
            "after not preserved:\n{refreshed}"
        );
        assert!(
            refreshed.contains('X'),
            "new block content missing:\n{refreshed}"
        );
        assert!(
            !refreshed.contains("OLD"),
            "old block content leaked:\n{refreshed}"
        );
    }

    #[test]
    fn splice_refuses_a_stray_begin_sentinel_without_a_matching_end() {
        let block = "<!-- BEGIN dent8 managed block (generated by `dent8 export`; edits inside are overwritten) -->\nX\n<!-- END dent8 managed block -->";
        // An orphan BEGIN (no END) followed by human content: appending would let the next export
        // match the orphan BEGIN and delete that content. Refuse instead.
        let orphan = "# Title\n\n<!-- BEGIN dent8 managed block (generated by `dent8 export`; edits inside are overwritten) -->\nprecious human content\n";
        assert!(
            splice_managed_block(Some(orphan), block).is_err(),
            "an unterminated BEGIN sentinel must be refused"
        );
        // Orphan END, duplicate BEGINs, and END-before-BEGIN are all refused too.
        let orphan_end = "text\n<!-- END dent8 managed block -->\n";
        assert!(splice_managed_block(Some(orphan_end), block).is_err());
        let two_begins = format!(
            "{block}\n<!-- BEGIN dent8 managed block (generated by `dent8 export`; edits inside are overwritten) -->\n"
        );
        assert!(splice_managed_block(Some(&two_begins), block).is_err());
    }

    #[test]
    fn splice_ignores_sentinels_inside_a_fenced_code_block() {
        let block = "<!-- BEGIN dent8 managed block (generated by `dent8 export`; edits inside are overwritten) -->\nX\n<!-- END dent8 managed block -->";
        // A file whose ONLY sentinels live inside a fenced example (like docs/native-memory.md):
        // the fenced pair must be ignored, so this is treated as "no block present" and a fresh
        // block is appended — leaving the fenced example byte-for-byte intact.
        let fenced_example = format!(
            "# Docs\n\nExample block:\n\n```text\n{BEGIN_SENTINEL}\ninside the example — must not be touched\n{END_SENTINEL}\n```\n"
        );
        let (spliced, kind) =
            splice_managed_block(Some(&fenced_example), block).expect("append past fenced example");
        assert_eq!(kind, BlockOutcome::Appended);
        assert!(
            spliced.starts_with(&fenced_example),
            "fenced example not preserved:\n{spliced}"
        );
        assert!(
            spliced.contains("inside the example — must not be touched"),
            "fenced example interior overwritten:\n{spliced}"
        );
        assert!(
            spliced.contains("\nX\n"),
            "fresh block not appended:\n{spliced}"
        );
    }

    #[test]
    fn splice_refreshes_the_real_block_and_leaves_a_fenced_example_untouched() {
        let block = "<!-- BEGIN dent8 managed block (generated by `dent8 export`; edits inside are overwritten) -->\nNEW\n<!-- END dent8 managed block -->";
        // A real (non-fenced) managed block PLUS a fenced example of the same sentinels. Only the
        // real block is refreshed; the fenced example interior survives.
        let real = "<!-- BEGIN dent8 managed block (generated by `dent8 export`; edits inside are overwritten) -->\nOLD\n<!-- END dent8 managed block -->";
        let fenced = format!(
            "\n\n## Example\n\n```text\n{BEGIN_SENTINEL}\nfenced sample body\n{END_SENTINEL}\n```\n"
        );
        let file = format!("# Title\n\n{real}{fenced}");
        let (spliced, kind) = splice_managed_block(Some(&file), block).expect("refresh real block");
        assert_eq!(kind, BlockOutcome::Refreshed);
        assert!(
            spliced.contains("NEW"),
            "real block not refreshed:\n{spliced}"
        );
        assert!(!spliced.contains("OLD"), "old body leaked:\n{spliced}");
        assert!(
            spliced.contains("fenced sample body"),
            "fenced example interior overwritten:\n{spliced}"
        );
        assert!(
            spliced.ends_with(&fenced),
            "fenced example not preserved:\n{spliced}"
        );
    }

    #[test]
    fn splice_still_refuses_a_stray_non_fenced_sentinel_beside_a_fenced_example() {
        let block = "<!-- BEGIN dent8 managed block (generated by `dent8 export`; edits inside are overwritten) -->\nX\n<!-- END dent8 managed block -->";
        // An orphan (non-fenced) BEGIN with no matching END, next to a well-formed fenced example.
        // The fenced pair is ignored; the lone non-fenced BEGIN is still a stray → refuse.
        let orphan = format!(
            "# Title\n\n{BEGIN_SENTINEL}\nprecious human content\n\n```text\n{BEGIN_SENTINEL}\nexample\n{END_SENTINEL}\n```\n"
        );
        assert!(
            splice_managed_block(Some(&orphan), block).is_err(),
            "a stray non-fenced BEGIN must still be refused"
        );
    }

    #[test]
    fn splice_refuses_a_file_that_ends_inside_an_unclosed_fence() {
        let block = "<!-- BEGIN dent8 managed block (generated by `dent8 export`; edits inside are overwritten) -->\nX\n<!-- END dent8 managed block -->";
        // An unclosed ``` fence swallows the real managed block that follows it, so the scan finds
        // zero non-fenced sentinels. Appending would nest a fresh block inside the never-closed
        // fence and repeated exports would keep appending (non-idempotent). Refuse instead.
        let unclosed =
            format!("# Title\n\n```text\nsome example\n{BEGIN_SENTINEL}\nOLD\n{END_SENTINEL}\n");
        let scan = managed_block_sentinels(&unclosed);
        assert!(scan.unclosed_fence, "fence must be reported open at EOF");
        assert!(scan.begins.is_empty() && scan.ends.is_empty());
        let err = splice_managed_block(Some(&unclosed), block).expect_err("must refuse");
        assert!(
            err.contains("unclosed code fence"),
            "unexpected message: {err}"
        );
        // A closed fence with the same content is fine (refresh, not append/grow).
        let closed = format!("{unclosed}```\n");
        assert!(
            !managed_block_sentinels(&closed).unclosed_fence,
            "closing the fence must expose the real block"
        );
    }

    #[test]
    fn dominant_line_ending_prefers_crlf_only_when_it_wins() {
        assert_eq!(dominant_line_ending(""), "\n", "empty defaults to LF");
        assert_eq!(
            dominant_line_ending("no newline"),
            "\n",
            "no newline defaults to LF"
        );
        assert_eq!(dominant_line_ending("a\nb\n"), "\n");
        assert_eq!(dominant_line_ending("a\r\nb\r\n"), "\r\n");
        // Tie goes to LF.
        assert_eq!(dominant_line_ending("a\r\nb\n"), "\n");
    }

    #[test]
    fn splice_emits_the_block_with_the_files_crlf_ending() {
        let block = "<!-- BEGIN dent8 managed block (generated by `dent8 export`; edits inside are overwritten) -->\nX\n<!-- END dent8 managed block -->";

        // Append into a CRLF file: the emitted block uses CRLF, existing bytes preserved.
        let crlf = "# Title\r\n\r\nHuman prose.\r\n";
        let (appended, kind) = splice_managed_block(Some(crlf), block).expect("append crlf");
        assert_eq!(kind, BlockOutcome::Appended);
        assert!(
            appended.starts_with(crlf),
            "existing CRLF bytes not preserved:\n{appended:?}"
        );
        assert!(
            appended.contains("edits inside are overwritten) -->\r\nX\r\n<!-- END"),
            "block not emitted with CRLF:\n{appended:?}"
        );
        assert!(
            !appended.contains("-->\nX"),
            "block leaked an LF ending:\n{appended:?}"
        );

        // Refresh a CRLF file: the new block uses CRLF and the surrounding CRLF text survives.
        let old = "<!-- BEGIN dent8 managed block (generated by `dent8 export`; edits inside are overwritten) -->\r\nOLD\r\n<!-- END dent8 managed block -->";
        let file = format!("# Title\r\n\r\n{old}\r\n\r\nAfter.\r\n");
        let (refreshed, kind) = splice_managed_block(Some(&file), block).expect("refresh crlf");
        assert_eq!(kind, BlockOutcome::Refreshed);
        assert!(
            refreshed.contains("\r\nX\r\n"),
            "refreshed block not CRLF:\n{refreshed:?}"
        );
        assert!(
            !refreshed.contains("OLD"),
            "old body leaked:\n{refreshed:?}"
        );
        assert!(
            refreshed.ends_with("\r\n\r\nAfter.\r\n"),
            "trailing CRLF text lost:\n{refreshed:?}"
        );
        assert!(
            !refreshed.contains("\r\r"),
            "doubled CR introduced:\n{refreshed:?}"
        );
    }

    #[test]
    fn splice_keeps_lf_files_on_lf() {
        let block = "<!-- BEGIN dent8 managed block (generated by `dent8 export`; edits inside are overwritten) -->\nX\n<!-- END dent8 managed block -->";
        let lf = "# Title\n\nHuman prose.\n";
        let (appended, _) = splice_managed_block(Some(lf), block).expect("append lf");
        assert!(
            !appended.contains('\r'),
            "LF file must not gain CR:\n{appended:?}"
        );
    }

    #[test]
    fn value_containing_the_receipt_token_survives_parsing() {
        // A Text value that itself contains the literal receipt-comment token must not be
        // truncated: the split is on the LAST occurrence, which is the trailing receipt comment.
        let raw = "a value with a  <!-- dent8 receipt look-alike inside";
        let encoded = encode_block_value(&FactValue::Text(raw.to_string())).expect("encode");
        let line = format!(
            "- `dent8://repo/demo/note` = {encoded}  <!-- dent8 receipt fact=fact:repo:demo:note:0 event_hash=abc authority=high source=source:human -->"
        );
        let parsed = parse_receipt_line(&line)
            .expect("has a marker")
            .expect("well-formed");
        assert_eq!(parsed.value, raw, "value must survive intact");
        assert_eq!(parsed.authority.as_deref(), Some("high"));
    }
}
