#!/usr/bin/env bash
# Start the packaged operated-witness split (Postgres + signer + publisher + monitor).
#
# Writes a writer env file (no private key) that agents/CLI can source to use the store.
#
# Usage (from repo root):
#   scripts/operated-witness-up.sh
#   DENT8_WITNESS_DB_PORT=55432 scripts/operated-witness-up.sh
#   DENT8_WITNESS_ALERT_WEBHOOK=https://hooks.example/… scripts/operated-witness-up.sh
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
COMPOSE_DIR="$ROOT/examples/witness-operated"
PROJECT="${COMPOSE_PROJECT_NAME:-dent8-ops}"
PORT="${DENT8_WITNESS_DB_PORT:-55432}"
PUBLISHED_DIR="${DENT8_WITNESS_PUBLISHED_DIR:-$COMPOSE_DIR/published}"
WRITER_ENV="${DENT8_OPERATED_WRITER_ENV:-$ROOT/.dent8/operated-witness.env}"

mkdir -p "$PUBLISHED_DIR" "$(dirname "$WRITER_ENV")"
# Ensure host published dir is writable by the container user (uid of dent8 in image).
chmod 777 "$PUBLISHED_DIR" 2>/dev/null || true

export COMPOSE_PROJECT_NAME="$PROJECT"
export DENT8_WITNESS_DB_PORT="$PORT"
export DENT8_WITNESS_PUBLISHED_DIR="$PUBLISHED_DIR"
export SIGN_INTERVAL_SECONDS="${SIGN_INTERVAL_SECONDS:-5}"
export PUBLISH_INTERVAL_SECONDS="${PUBLISH_INTERVAL_SECONDS:-5}"
export MONITOR_INTERVAL_SECONDS="${MONITOR_INTERVAL_SECONDS:-5}"

COMPOSE=(docker compose -p "$PROJECT" -f "$COMPOSE_DIR/compose.yml")

echo "operated-witness: project=$PROJECT db=localhost:$PORT published=$PUBLISHED_DIR"
up_args=(up -d)
if [ "${DENT8_WITNESS_BUILD:-1}" != "0" ]; then
  up_args+=(--build)
fi
up_args+=(db signer publisher monitor)
"${COMPOSE[@]}" "${up_args[@]}"

# Wait for db
echo "operated-witness: waiting for postgres..."
for _ in $(seq 1 60); do
  if "${COMPOSE[@]}" exec -T db pg_isready -U postgres -d dent8 >/dev/null 2>&1; then
    break
  fi
  sleep 1
done

# Writer env: shared store + public verification only (never the private key).
cat >"$WRITER_ENV" <<ENV
# Generated by scripts/operated-witness-up.sh — writer / agent side of the operated witness.
# DO NOT put DENT8_WITNESS_KEY here.
export DENT8_STORE_URL='postgres://postgres:dent8@127.0.0.1:${PORT}/dent8'
export DENT8_WITNESS_PUBKEY='${PUBLISHED_DIR}/witness.key.pub'
# Optional: local cache of heads for doctor; verification of record is the published file.
export DENT8_WITNESS_LOG='${PUBLISHED_DIR}/local-writer-witness.jsonl'
# Published sequence the writer must not rewrite (monitor + host scripts use this).
export DENT8_WITNESS_PUBLISHED='${PUBLISHED_DIR}/heads.jsonl'
ENV

echo "operated-witness: writer env -> $WRITER_ENV"
echo "  source it in a shell with a postgres-capable dent8 binary, e.g.:"
echo "    cargo build -p dent8-cli --features postgres"
echo "    set -a; . $WRITER_ENV; set +a"
echo "    dent8 witness doctor writer"
echo "    dent8 assert repo:ops smoke ok --authority high --source source:owner"
echo "  status: scripts/operated-witness-status.sh"
echo "  down:   scripts/operated-witness-down.sh"
echo "  smoke:  scripts/operated-witness-smoke.sh"
